### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Zhangwenyao1** [DylanAuty/PromptLearningCLIP-MDE#1]
When I run "python main.py -c ./params/basicParams.yaml ".
The error occured:

38.4 M    Trainable params
63.6 M    Non-trainable params
102 M     Total params
408.043   Total estimated model params size (MB)
Segmentation fault (core dumped)

**Comment by LuckySun11** [comment]
Have you solved this problem? How did you do it? Thank you
